name: chateo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^4.17.5
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7  # Use the latest version
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/chateo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/image/Illustration.png
