// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP55ohjpKse_f1gRlKTV5RTCdeQjnfiH8',
    appId: '1:998581806229:web:d6506688fb7170d31f679c',
    messagingSenderId: '998581806229',
    projectId: 'chateo-d5757',
    authDomain: 'chateo-d5757.firebaseapp.com',
    storageBucket: 'chateo-d5757.firebasestorage.app',
    measurementId: 'G-MY57LKHJHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXpe6hr4ZE-drUXibWf293IE141wYn_U',
    appId: '1:998581806229:android:a5a0d3261c4c224e1f679c',
    messagingSenderId: '998581806229',
    projectId: 'chateo-d5757',
    storageBucket: 'chateo-d5757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQ-W6yXX09pYZQEdrX0JVioeRwSy4Jk8',
    appId: '1:998581806229:ios:f1a3f88097cb362b1f679c',
    messagingSenderId: '998581806229',
    projectId: 'chateo-d5757',
    storageBucket: 'chateo-d5757.firebasestorage.app',
    iosBundleId: 'com.example.chateo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQ-W6yXX09pYZQEdrX0JVioeRwSy4Jk8',
    appId: '1:998581806229:ios:f1a3f88097cb362b1f679c',
    messagingSenderId: '998581806229',
    projectId: 'chateo-d5757',
    storageBucket: 'chateo-d5757.firebasestorage.app',
    iosBundleId: 'com.example.chateo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP55ohjpKse_f1gRlKTV5RTCdeQjnfiH8',
    appId: '1:998581806229:web:6799c2da05520bf61f679c',
    messagingSenderId: '998581806229',
    projectId: 'chateo-d5757',
    authDomain: 'chateo-d5757.firebaseapp.com',
    storageBucket: 'chateo-d5757.firebasestorage.app',
    measurementId: 'G-1ZVDECMBT8',
  );
}
